version: '3.3'
services:
  bot_template:
    build: .
    container_name: bot_template
    image: bot_template
    restart: always
    # ports:
    #   - "3939:3939"
    volumes:
      - type: bind
        source: $PWD/static
        target: /app/static
    environment:
      # - ENV=production
      - ENV=debug
